In [54]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

In [55]:
df_left = DataFrame({'key':['x','y','z','x','y'], 'data':range(5)})

In [56]:
df_left

key  data
0   x     0
1   y     1
2   z     2
3   x     3
4   y     4

In [80]:
df_right = DataFrame({'group_data':[10,20]}, index =['x','y'])
df_right

group_data
x          10
y          20

In [66]:
pd.merge(df_left, df_right, left_on = 'key', right_index = True)

key  data  group_data
0   x     0          10
3   x     3          10
1   y     1          20
4   y     4          20

In [64]:
pd.merge(df_left, df_right, right_on = 'group_data', left_index = True)   

key  data  group_data
x   y     1           1

In [67]:
df_left_hr = DataFrame({'key1':['SF', 'SF', 'SF', 'LA', 'LA'],
                       'key2':[10,20,30,20,30],
                       'data_set':np.arange(5)})  ##left table me specifically columns

In [68]:
df_left_hr

key1  key2  data_set
0   SF    10         0
1   SF    20         1
2   SF    30         2
3   LA    20         3
4   LA    30         4

In [69]:
df_right_hr = DataFrame(np.arange(10).reshape(5,2), index = [['LA', 'LA', 'SF', 'SF', 'SF'],
                                                             [20,10,10,10,20]], columns = ['col_1', 'col_2'])

In [41]:
df_right_hr

col_1  col_2
LA 20      0      1
   10      2      3
SF 10      4      5
   10      6      7
   20      8      9

In [70]:
pd.merge(df_left_hr, df_right_hr, left_on = ['key1', 'key2'], right_index = True) ## key1 key2 columns  compare to indexes of right 

key1  key2  data_set  col_1  col_2
0   SF    10         0      4      5
0   SF    10         0      6      7
1   SF    20         1      8      9
3   LA    20         3      0      1

In [71]:
pd.merge(df_left_hr, df_right_hr, left_on = ['key2'] , right_index = True)

ValueError: len(left_on) must equal the number of levels in the index of "right"

In [72]:
df_left

key  data
0   x     0
1   y     1
2   z     2
3   x     3
4   y     4

In [73]:
df_right

group_data
x          10
y          20

In [81]:
df_left.join(df_right)

key  data  group_data
0   x     0         NaN
1   y     1         NaN
2   z     2         NaN
3   x     3         NaN
4   y     4         NaN

In [15]:
## concat

In [82]:
arr1 = np.arange(9).reshape(3,3)

In [83]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
np.concatenate([arr1,arr1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [84]:
np.concatenate([arr1, arr1], axis = 1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [85]:
np.concatenate([arr1, arr1], axis = 0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [86]:
ser1 = Series([0,1,2], index = ['T', 'U', 'V'])

In [87]:
ser2 = Series([3,4], index = ['X', 'Y']) 

In [88]:
ser1

T    0
U    1
V    2
dtype: int64

In [89]:
ser2

X    3
Y    4
dtype: int64

In [25]:
pd.concat([ser1, ser2], axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [26]:
pd.concat([ser1, ser2], keys = ['Series 1', 'Series 2'])

Series 1  T    0
          U    1
          V    2
Series 2  X    3
          Y    4
dtype: int64

df1 = DataFrame(np.random.randn(4,3), columns = ['X', 'Y', 'Z'])

In [28]:
df2 = DataFrame(np.random.randn(3,3), columns = ['Y', 'Q', 'X'])

In [29]:
df1

X         Y         Z
0 -0.692229 -0.026559 -0.088011
1 -0.977933 -1.021075  0.190905
2  0.351792 -0.641273 -0.889909
3 -0.069807 -1.557867 -1.742015

In [30]:
df2

Y         Q         X
0  0.006127  0.042366 -0.909290
1  1.162981  0.303117 -0.044695
2  0.032115 -1.171820 -1.415631

In [31]:
pd.concat([df1, df2])

X         Y         Z         Q
0 -0.692229 -0.026559 -0.088011       NaN
1 -0.977933 -1.021075  0.190905       NaN
2  0.351792 -0.641273 -0.889909       NaN
3 -0.069807 -1.557867 -1.742015       NaN
0 -0.909290  0.006127       NaN  0.042366
1 -0.044695  1.162981       NaN  0.303117
2 -1.415631  0.032115       NaN -1.171820

In [32]:
pd.concat([df1, df2], ignore_index = True)

X         Y         Z         Q
0 -0.692229 -0.026559 -0.088011       NaN
1 -0.977933 -1.021075  0.190905       NaN
2  0.351792 -0.641273 -0.889909       NaN
3 -0.069807 -1.557867 -1.742015       NaN
4 -0.909290  0.006127       NaN  0.042366
5 -0.044695  1.162981       NaN  0.303117
6 -1.415631  0.032115       NaN -1.171820