In [2]:
import pandas as pd
import numpy as np
from sklearn import datasets, linear_model
import matplotlib.pyplot as plt


In [3]:
diabetes = datasets.load_diabetes()

In [4]:
diabetes.DESCR

'.. _diabetes_dataset:\n\nDiabetes dataset\n----------------\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\n**Data Set Characteristics:**\n\n  :Number of Instances: 442\n\n  :Number of Attributes: First 10 columns are numeric predictive values\n\n  :Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n  :Attribute Information:\n      - age     age in years\n      - sex\n      - bmi     body mass index\n      - bp      average blood pressure\n      - s1      tc, T-Cells (a type of white blood cells)\n      - s2      ldl, low-density lipoproteins\n      - s3      hdl, high-density lipoproteins\n      - s4      tch, thyroid stimulating hormone\n      - s5      ltg, lamotrigine\n      - s6      glu, blood sugar level\n\nNo

In [80]:
diabetes.target.shape

(442,)

In [5]:
diabetes.data

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]])

In [64]:
##diabetes.keys()

In [65]:
##diabetes.feature_names

In [81]:
# diabetes_x = diabetes.data[:,np.newaxis,2]
diabetes_x = diabetes.data

In [82]:
diabetes_x.shape

(442, 10)

In [83]:
diabetes_x_train = diabetes_x[:-30]
diabetes_x_train.shape

(412, 10)

In [84]:
diabetes_x_test = diabetes_x[-30:]

In [85]:
diabetes_x_test

array([[ 7.44012909e-02, -4.46416365e-02,  8.54080721e-02,
         6.31868033e-02,  1.49424745e-02,  1.30909518e-02,
         1.55053592e-02, -2.59226200e-03,  6.20931562e-03,
         8.59065477e-02],
       [-5.27375548e-02, -4.46416365e-02, -8.16893766e-04,
        -2.63278347e-02,  1.08146159e-02,  7.14113104e-03,
         4.86400995e-02, -3.94933829e-02, -3.58167281e-02,
         1.96328371e-02],
       [ 8.16663678e-02,  5.06801187e-02,  6.72779075e-03,
        -4.52298700e-03,  1.09883222e-01,  1.17056241e-01,
        -3.23559322e-02,  9.18746074e-02,  5.47240033e-02,
         7.20651633e-03],
       [-5.51455498e-03, -4.46416365e-02,  8.88341490e-03,
        -5.04279296e-02,  2.59500973e-02,  4.72241342e-02,
        -4.34008457e-02,  7.12099798e-02,  1.48227108e-02,
         3.06440941e-03],
       [-2.73097857e-02, -4.46416365e-02,  8.00190118e-02,
         9.87631337e-02, -2.94491268e-03,  1.81013272e-02,
        -1.76293810e-02,  3.31191734e-03, -2.95276227e-02,
         3.

In [86]:
diabetes_y_train = diabetes.target[:-30]

In [87]:
diabetes_y_train.shape

(412,)

In [88]:
diabetes_y_test = diabetes.target[-30:]

In [89]:
diabetes_y_test.shape

(30,)

In [90]:
model = linear_model.LinearRegression()

In [91]:
model.fit(diabetes_x_train, diabetes_y_train)

LinearRegression()

In [108]:
y = model.predict(diabetes_x_test)

# y = model.predict([[2,3,4,5,6,1,1,1,1,1]])
y

array([234.04069476, 122.92246614, 166.35433115, 174.39222892,
       226.94851442, 151.82190227, 100.94358512,  83.08956073,
       143.1298667 , 192.67823683, 197.98434449, 154.37965196,
       173.16544327, 112.38886823, 164.20528828, 131.63666326,
       258.66439447, 101.4126313 , 117.87101994, 123.5370635 ,
       219.5123662 ,  62.09123359, 133.09435929, 121.33048447,
        53.51502538, 193.125764  , 104.69007361, 123.68983031,
       211.27336049,  53.87045485])

In [93]:
from sklearn.metrics import mean_squared_error

In [94]:
mean_squared_error(diabetes_y_test, y)

1826.5364191345434

In [95]:
model.coef_

array([  -1.16924976, -237.18461486,  518.30606657,  309.04865826,
       -763.14121622,  458.90999325,   80.62441437,  174.32183366,
        721.49712065,   79.19307944])

In [96]:
model.intercept_

153.05827988224112

In [97]:
import matplotlib.pyplot as plt 

In [99]:
# plt.scatter(diabetes_x_test, diabetes_y_test)
# plt.plot(diabetes_x_test, y)

ValueError: Expected 2D array, got 1D array instead:
array=[1].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.